### PR TITLE
Pass through "..." from SL.randomForest to randomForest

### PR DESCRIPTION
**Pull request by saraemoore**
To allow access to additional randomForest tuning parameters and objects to be passed back

### CODE REVIEW

**Comment by ecpolley** [comment]
Do you have specific parameters we can add to the `SL.randomForest` function? this is safer than moving the `...` into the internal call.

**Comment by saraemoore** [comment]
Yes -- adding `importance` would be sufficient for my application.

**Comment by ecpolley** [comment]
OK, I added `importance` to the `SL.randomForest` function here.
Thanks!

**Comment by saraemoore** [comment]
Thank you!

**Pull request closed without merging**
