### PR TITLE
SL.lm, SL.glm: don't save model.matrix element by default

### PR DESCRIPTION
**Pull request by ck37**
Hello,

This modifies SL.lm and SL.glm to not save the model.matrix to their fit element by default, which conserves memory. While I was at it I added roxygen, tests, and support for matrix data objects.

Thanks,
Chris

### CODE REVIEW

**Comment by ecpolley** [comment]
Thanks, my thought is it would be better to default to `TRUE` since this is the default for `glm`. Also a good idea to spell out `FALSE` instead of `F`. That ruins the fun of sneaking something like `F <- TRUE` into someones .Rprofile

Only the full `TRUE` and `FALSE` are reserved words. `T` and `F` are partial matches and could also be object names.

**Comment by ck37** [comment]
Ok I've made those changes. Blabbing a bit --

Personally though I don't see the benefit of using that extra memory in lm/glm when there is no reason to use the model.matrix that is saved. On the negligible chance that someone is using that we're defaulting to wasting the memory in everyone else's superlearners.

I don't mind using TRUE & FALSE but T and F don't seem to be partial matches, they are objects defined in the base environment:
```r
> # Check on partial matching issue.
> T
[1] TRUE
> TRue = F
> TRue
[1] FALSE
> T
[1] TRUE
> TRUETHY = F
> # Still no partial matching.
> T
[1] TRUE
> # T is in the base environment.
> pryr::where("T")
<environment: base>
> # Can redefine but only in GlobalEnv
> T = F
> T
[1] FALSE
> pryr::where("T")
<environment: R_GlobalEnv>
```

For me the TRUE/FALSE issue is another example of R being unnecessarily weird, when T & F work fine in pretty much every other language. I feel similarly about `<-` & `=`.

**Comment by ck37** [comment]
Although now that I review https://en.wikipedia.org/wiki/Boolean_data_type maybe it's just in my head that most other languages support T/F.

**Comment by ecpolley** [comment]
OK, not a partial match, but only TRUE and FALSE are reserved, `help("reserved")`

**Comment by ecpolley** [comment]
And of course the `F <- TRUE` (yes, the `<-` is the correct way to do that 👍 ) is unlikely. But you can have variables with those names and cause confusing error messages.

**Pull request merged**
