### PR TITLE
SL.lm: for binomial family bound predictions to [0, 1]

### PR DESCRIPTION
**Pull request by ck37**
Hi,

This is a quick update to the SL.lm wrapper so that binomial family predictions are restricted to [0, 1].

Thanks,
Chris

### CODE REVIEW

**Comment by ecpolley** [comment]
You might think about adding a tolerance to the truncation, sometimes having probability values of exactly 0 or exactly 1 can cause problems downstream (e.g. if using log(P) or log(1-P))

**Comment by ck37** [comment]
Yeah I considered that, but ended up just going with a simple implementation to respect the binomial family. I think the log issue could warrant a more general fix for the methods that need that.

**Comment by ecpolley** [comment]
although if we wanted to respect the binomial family, we should use `glm`

**Comment by ck37** [comment]
Yep, I'm only using this for historical comparison to a project that used OLS for classification, which comes up on occasion.

**Pull request merged**
