### PR TITLE
supplemental additions: License, site, README cleanup

### PR DESCRIPTION
**Pull request by nhejazi**
* updates `README.md` to include [project status badge](http://www.repostatus.org/) and license badge (MIT), as well as mention of MIT licensing + other minor changes

* adds MIT license (listing Eric C. Polley as copyright holder) to enable software to be legally available to others (this should have been there already)

* adds `docs` subdirectory from the [`pkgdown` package]() to build a minimal website providing package documentation for users. See [here](http://nimahejazi.org/SuperLearner), ideally site would be readily available under http://ecpolley.github.io/SuperLearner or similar URL.

* minor updates to the contents of the file `DESCRIPTION`, including contributor credit for Nima Hejazi (packaging changes noted above)

### CODE REVIEW

**Comment by ecpolley** [comment]
Hi Nima,  One problem is the package is under GPL-3, not the MIT license. Does pkgdown provide anything other than an HTML format for the Rd documents?

**Comment by nhejazi** [comment]
Hi Eric, apologies for the mixup re: licensing. I'll switch that over to GPL-3 (really, I should have read the description file more closely). I'm not sure I understand the question on the format produced by `pkgdown`? (since it's purpose is to generate a simple site, HTML seems necessary)

**Comment by ck37** [comment]
It would be good to update your roxygen to the latest version too (~6.0.1) because right now the PR is downgrading to roxygen 5.

On pkgdown, can the compilation command be put into a Makefile and/or automated (eg travis-sphynx) so that it doesn't have to be run manually?

-ck.mobile

**Comment by ecpolley** [comment]
For pkgdown, I guess I see this as redundant with the current package help documentation, with the only difference being it generates HTML code for a webpage versus the Rd documents within R. Is that correct?

**Comment by nhejazi** [comment]
Eric -- `pkgdown` is not meant to do much more than what the Rd documents do, that is, it is entirely supplementary. The motivation behind having a separate set of webpages for SL is to allow interested parties to explore the documentation without being forced to do so from within R, or without browsing CRAN. It is really entirely supplementary, but encourages people to explore the package more.

Chris -- thanks for noting that my roxygen was out of date, I'll fix that. In regard to automating the use of `pkgdown` in a manner similar to travis-sphinx, I have seen that done (e.g., the [`zoon` project repo](https://github.com/zoonproject/zoon/issues/346)), though the approach is rather messy and not supported within `pkgdown`. That said, the docs generated by `pkgdown` are meant to be supplementary/exploratory, so having them auto-build seems like overkill to me, esp. given that this project is stable at this point (I wouldn't expect major changes to the docs...)

**Pull request closed without merging**
