### PR TITLE
Add vignette: "Guide to SuperLearner"

### PR DESCRIPTION
**Pull request by ck37**
Hello,

Here is a conversion of ck37/superlearner-guide to a vignette, due to popular demand. I changed the dataset to Boston to reduce data prep complexity and made some tweaks to reduce computation a little, but otherwise it's pretty much the same. It still takes ~5 minutes to build unfortunately. There is also plenty more functionality that we should eventually add to it.

Thanks,
Chris

### CODE REVIEW

**Comment by ecpolley** [comment]
Awesome, thanks. We might need to review and modify to meet CRAN requirements for build time, but this looks great

**Comment by ck37** [comment]
Sounds good, yeah happy to make some build time improvements as needed.

I investigated a little bit and I believe that CRAN does not check vignette build time, but I might be wrong:
- http://r-pkgs.had.co.nz/check.html#check-checks
- http://r-pkgs.had.co.nz/vignettes.html#vignette-cran
- https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-package-vignettes

I need to do some work to speed up the test suite at some point too.

**Comment by ecpolley** [comment]
hmm, don't see it either. I've been questioned in the past about build time, but maybe that is less of a concern now. Package size less than 5mb shouldn't be a problem.

**Comment by ck37** [comment]
Well looks like this may now cause a build issue even though it didn't pre-commit for me :/

```
checking re-building of vignette outputs ... WARNING
Error in re-building vignettes:
  ...
Quitting from lines 364-390 (Guide-to-SuperLearner.Rmd) 
Error: processing vignette 'Guide-to-SuperLearner.Rmd' failed with diagnostics:
4 simultaneous processes spawned
Execution halted
```

I'm not sure if there is an easy fix to have devtools::check() not execute the parallel parts that are triggering the error.

**Pull request merged**
