### PR TITLE
New wrapper: biglasso, a glmnet alternative implementation

### PR DESCRIPTION
**Pull request by ck37**
Hello,

Here is a wrapper for biglasso, which is an alternative to glmnet that is in theory more memory & computation efficient.

Thanks,
Chris

### CODE REVIEW

**Comment by ecpolley** [comment]
Hi Chris, looks like the SL.biglasso is throwing errors on Travis, in the case with only a single X variable. Any thoughts?

**Comment by ck37** [comment]
Yeah I saw that :/. Strangely there was no error in my original PR & commit, and appveyor still has no error. So I'm not sure why Travis is now generating errors in both the example and the tests, and I'm not getting the errors on my own computer. There isn't a test with a single covariate so that doesn't seem to be the issue. I'll keep investigating though and try to get it resolved.

**Comment by ecpolley** [comment]
I wonder if it is a version issue, looks like 2 version on CRAN right now (1.3-3 and 1.3-5)

**Comment by ck37** [comment]
Very good point, that appears to be the issue. biglasso was updated today on CRAN and there seems to be some real changes: https://github.com/YaohuiZeng/biglasso/commit/b33a1f88691c9d86536a0a4981157daf3a61ed9c

**Pull request merged**
